#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class CreateUserCommand extends Command {
	
	protected function configure() {
		$this
		  // the name of the command (the part after "bin/console")
		  ->setName('app:create-users')
		  // the short description shown while running "php bin/console list"
		  ->setDescription('Creates new users.')
		  // the full command description shown when running the command with
		  // the "--help" option
		  ->setHelp("This command allows you to create users...");
	}
	
	protected function execute(InputInterface $input, OutputInterface $output) {
		$output->writeln("test");
	}
}

$application = new Application();

$application->add(new CreateUserCommand());
$application->run();
